# Generated by Django 5.2.5 on 2025-11-22 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tenant_id', models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('min_stock', models.IntegerField(default=0)),
                ('qr_payload', models.CharField(editable=False, max_length=120, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('nfc_tag_uid', models.CharField(blank=True, max_length=64)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('consumption_date', models.DateField(blank=True, null=True)),
                ('track_open_state', models.BooleanField(default=False, help_text='Si está activo, este producto tiene etapa de ‘abierto’ con segunda caducidad.')),
                ('default_open_shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Días que dura tras abrir (p. ej. 7). Se usa si no se indican días manualmente.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('name_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=220)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False)),
                ('quantity', models.IntegerField(help_text='Positivo para entradas, negativo para salidas')),
                ('movement_type', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit'), ('ADJ', 'Adjust'), ('AUD', 'Audit')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('opened_units', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_expires_at', models.DateTimeField(blank=True, null=True)),
                ('depleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_depleted', models.BooleanField(db_index=True, default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['entry_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'parent', 'name'), name='uniq_location_per_parent_tenant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'location', 'name_normalized'], name='inventory_p_tenant__fb8bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'name'], name='inventory_p_tenant__6738c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='product_min_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'location', 'name_normalized'), name='uniq_product_per_location_tenant_norm'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batch_quantity_gte_0'),
        ),
    ]
