# Generated by Django 5.2.5 on 2025-08-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_nestedlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='code',
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location'),
        ),
        migrations.DeleteModel(
            name='NestedLocation',
        ),
    ]
