# Generated by Django 5.2.8 on 2025-12-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_brand_batch_dimensions_batch_estimated_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('app_version', models.CharField(default='0.1-alpha (tester-local)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id',), name='uniq_appmeta_per_tenant')],
            },
        ),
    ]
