# Generated by Django 5.2.5 on 2025-10-22 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='batch',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False),
        ),
        migrations.AddField(
            model_name='movement',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000001', editable=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'location'], name='inventory_p_tenant__9bb161_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'name'], name='inventory_p_tenant__6738c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'location', 'name'), name='uniq_product_per_location_tenant'),
        ),
    ]
