# Generated by Django 5.2.5 on 2025-10-23 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_uniq_product_per_location_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_tenant__9bb161_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'location', 'name_normalized'], name='inventory_p_tenant__fb8bd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'location', 'name_normalized'), name='uniq_product_per_location_tenant_norm'),
        ),
    ]
