# Generated by Django 5.2.5 on 2025-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_product_inventory_p_tenant__9bb161_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'parent', 'name'), name='uniq_location_per_parent_tenant'),
        ),
    ]
